# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_profile_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import easygui
from gui_main import importprofile


class Ui_Rent_Manager_ProfileSelect(object):
    def setupUi(self, Rent_Manager_ProfileSelect):
        Rent_Manager_ProfileSelect.setObjectName("Rent_Manager_ProfileSelect")
        Rent_Manager_ProfileSelect.resize(441, 248)
        Rent_Manager_ProfileSelect.setMinimumSize(QtCore.QSize(441, 248))
        Rent_Manager_ProfileSelect.setMaximumSize(QtCore.QSize(441, 248))
        Rent_Manager_ProfileSelect.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Rent_Manager_ProfileSelect.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Rent_Manager_ProfileSelect)
        self.centralwidget.setObjectName("centralwidget")
        self.new_profile = QtWidgets.QPushButton(self.centralwidget)
        self.new_profile.setGeometry(QtCore.QRect(50, 150, 121, 51))
        self.new_profile.setObjectName("new_profile")
        self.import_profile = QtWidgets.QPushButton(self.centralwidget)
        self.import_profile.setGeometry(QtCore.QRect(270, 150, 121, 51))
        self.import_profile.setObjectName("import_profile")
        self.import_profile.clicked.connect(importprofile())
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 141, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Rent_Manager_ProfileSelect.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Rent_Manager_ProfileSelect)
        self.statusbar.setObjectName("statusbar")
        Rent_Manager_ProfileSelect.setStatusBar(self.statusbar)

        self.retranslateUi(Rent_Manager_ProfileSelect)
        QtCore.QMetaObject.connectSlotsByName(Rent_Manager_ProfileSelect)
    


    def retranslateUi(self, Rent_Manager_ProfileSelect):
        _translate = QtCore.QCoreApplication.translate
        Rent_Manager_ProfileSelect.setWindowTitle(_translate("Rent_Manager_ProfileSelect", "Rent Manager - Profile Selection"))
        Rent_Manager_ProfileSelect.setWhatsThis(_translate("Rent_Manager_ProfileSelect", "<html><head/><body><p>Rent Manager - Profile Selection</p><p><br/></p></body></html>"))
        self.new_profile.setText(_translate("Rent_Manager_ProfileSelect", "New Profile"))
        self.import_profile.setText(_translate("Rent_Manager_ProfileSelect", "Import Profile"))
        self.label.setText(_translate("Rent_Manager_ProfileSelect", "Rent Manager"))
        self.label_3.setText(_translate("Rent_Manager_ProfileSelect", "by Jacob Du"))
