# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_send_charge.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_send_charge(object):
    def setupUi(self, send_charge):
        send_charge.setObjectName("send_charge")
        send_charge.resize(312, 388)
        self.centralwidget = QtWidgets.QWidget(send_charge)
        self.centralwidget.setObjectName("centralwidget")
        self.radio_rent = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_rent.setGeometry(QtCore.QRect(100, 20, 61, 21))
        self.radio_rent.setChecked(True)
        self.radio_rent.setObjectName("radio_rent")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label.setObjectName("label")
        self.radio_other = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_other.setGeometry(QtCore.QRect(170, 20, 61, 21))
        self.radio_other.setObjectName("radio_other")
        self.check_splitbyrent = QtWidgets.QCheckBox(self.centralwidget)
        self.check_splitbyrent.setGeometry(QtCore.QRect(10, 50, 201, 20))
        self.check_splitbyrent.setObjectName("check_splitbyrent")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 161, 16))
        self.label_2.setObjectName("label_2")
        self.text_requestmessage = QtWidgets.QLineEdit(self.centralwidget)
        self.text_requestmessage.setGeometry(QtCore.QRect(10, 130, 291, 21))
        self.text_requestmessage.setObjectName("text_requestmessage")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_3.setObjectName("label_3")
        self.text_charge_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.text_charge_amount.setGeometry(QtCore.QRect(120, 80, 181, 21))
        self.text_charge_amount.setObjectName("text_charge_amount")
        self.list_members_charged = QtWidgets.QListView(self.centralwidget)
        self.list_members_charged.setGeometry(QtCore.QRect(10, 180, 291, 141))
        self.list_members_charged.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list_members_charged.setObjectName("list_members_charged")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 161, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 330, 171, 32))
        self.pushButton.setObjectName("pushButton")
        send_charge.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(send_charge)
        self.statusbar.setObjectName("statusbar")
        send_charge.setStatusBar(self.statusbar)

        self.retranslateUi(send_charge)
        QtCore.QMetaObject.connectSlotsByName(send_charge)

    def retranslateUi(self, send_charge):
        _translate = QtCore.QCoreApplication.translate
        send_charge.setWindowTitle(_translate("send_charge", "Rent Manager - Send Charges"))
        self.radio_rent.setText(_translate("send_charge", "Rent"))
        self.label.setText(_translate("send_charge", "Charge Type"))
        self.radio_other.setText(_translate("send_charge", "Other"))
        self.check_splitbyrent.setText(_translate("send_charge", "Split by Rent Distribution"))
        self.label_2.setText(_translate("send_charge", "Venmo Request Message"))
        self.label_3.setText(_translate("send_charge", "Charge Amount"))
        self.label_4.setText(_translate("send_charge", "Members Charged"))
        self.pushButton.setText(_translate("send_charge", "Send Venmo Request"))
